import {
  cancelEmail,
  createApiKey,
  createAudience,
  createBroadcast,
  createContact,
  createDomain,
  deleteApiKey,
  deleteAudience,
  deleteBroadcast,
  deleteContact,
  deleteDomain,
  getAudience,
  getContact,
  getDomain,
  getEmail,
  listApiKeys,
  listAudiences,
  listBroadcasts,
  listContacts,
  listDomains,
  listEmails,
  sendBatchEmails,
  sendBroadcast,
  sendEmail,
  updateContact,
  updateDomain,
  updateEmail,
  verifyDomain,
} from './src/index.js';

export const block = {
  name: 'resend',
  tools: {
    sendEmail,
    sendBatchEmails,
    getEmail,
    updateEmail,
    cancelEmail,
    listEmails,
    createDomain,
    getDomain,
    updateDomain,
    deleteDomain,
    listDomains,
    verifyDomain,
    createApiKey,
    listApiKeys,
    deleteApiKey,
    createContact,
    getContact,
    updateContact,
    deleteContact,
    listContacts,
    createBroadcast,
    listBroadcasts,
    sendBroadcast,
    deleteBroadcast,
    createAudience,
    listAudiences,
    getAudience,
    deleteAudience,
  },
};

export default block;
