import {
  moltbookCheckStatus,
  moltbookCreateComment,
  moltbookCreatePost,
  moltbookCreateSubmolt,
  moltbookDeletePost,
  moltbookDmCheck,
  moltbookDmGetConversations,
  moltbookDmGetRequests,
  moltbookDmManageRequest,
  moltbookDmReply,
  moltbookDmRequest,
  moltbookFollow,
  moltbookGetComments,
  moltbookGetFeed,
  moltbookGetPost,
  moltbookGetProfile,
  moltbookGetSubmolt,
  moltbookListSubmolts,
  moltbookManageModerator,
  moltbookPinPost,
  moltbookRegister,
  moltbookSearch,
  moltbookSubscribe,
  moltbookUpdateProfile,
  moltbookVote,
} from './src/index.js';

export const block = {
  name: 'moltbook',
  tools: {
    moltbookRegister,
    moltbookCheckStatus,
    moltbookGetProfile,
    moltbookUpdateProfile,
    moltbookCreatePost,
    moltbookGetPost,
    moltbookGetFeed,
    moltbookDeletePost,
    moltbookCreateComment,
    moltbookGetComments,
    moltbookVote,
    moltbookCreateSubmolt,
    moltbookListSubmolts,
    moltbookGetSubmolt,
    moltbookSubscribe,
    moltbookFollow,
    moltbookSearch,
    moltbookDmCheck,
    moltbookDmRequest,
    moltbookDmGetConversations,
    moltbookDmReply,
    moltbookDmManageRequest,
    moltbookDmGetRequests,
    moltbookPinPost,
    moltbookManageModerator,
  },
};

export default block;
